export const GET_ALL_CURRENCIES = 'GET_ALL_CURRENCIES';
export const ERROR_LOADING_CURRENCIES = 'ERROR_LOADING_CURRENCIES';
export const SET_LOADING = 'SET_LOADING';
export const GET_RATE_TWO_CURRENCIES_SUCCESS =
  'GET_RATE_TWO_CURRENCIES_SUCCESS';
export const GET_RATE_TWO_CURRENCIES_FAIL = 'GET_RATE_TWO_CURRENCIES_FAIL';
export const GET_RATE_CHART_SUCCESS = 'GET_RATE_CHART_SUCCESS';
export const GET_RATE_CHART_FAIL = 'GET_RATE_CHART_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';
